// <auto-generated />
using System;
using IncidenciasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidenciasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924001012_AlignCurrentSchema")]
    partial class AlignCurrentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IncidenciasAPI.Models.AlertaIncidente", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_alerta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_alerta");

                    b.Property<int>("IdIncidente")
                        .HasColumnType("int")
                        .HasColumnName("id_incidente");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("mensaje");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdIncidente");

                    b.ToTable("alerta_inci");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Ciudadano", b =>
                {
                    b.Property<int>("IdCiudadano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_ciudadano");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCiudadano"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Localidad")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("localidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCiudadano");

                    b.ToTable("ciudadano");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_incidente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdCiudadano")
                        .HasColumnType("int")
                        .HasColumnName("id_ciudadano");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdCiudadano");

                    b.HasIndex("IdUsuario");

                    b.ToTable("incidente");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("EstadoReporte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado_reporte");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha");

                    b.Property<int>("IdIncidente")
                        .HasColumnType("int")
                        .HasColumnName("id_incidente");

                    b.Property<string>("Lugar")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lugar");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdIncidente");

                    b.ToTable("reporte");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.UsuarioRepo", b =>
                {
                    b.Property<int>("IdUsuarioRepo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_repo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuarioRepo"));

                    b.Property<string>("EstadoRepo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado_repo");

                    b.Property<DateTime>("FechaRepo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_repo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("LugarRepo")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("lugar_repo");

                    b.HasKey("IdUsuarioRepo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("usuario_repo");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.AlertaIncidente", b =>
                {
                    b.HasOne("IncidenciasAPI.Models.Incidente", "Incidente")
                        .WithMany("Alertas")
                        .HasForeignKey("IdIncidente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Incidente", b =>
                {
                    b.HasOne("IncidenciasAPI.Models.Ciudadano", "Ciudadano")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdCiudadano")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidenciasAPI.Models.Usuario", "Usuario")
                        .WithMany("Incidencias")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ciudadano");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Reporte", b =>
                {
                    b.HasOne("IncidenciasAPI.Models.Incidente", "Incidente")
                        .WithMany("Reportes")
                        .HasForeignKey("IdIncidente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.UsuarioRepo", b =>
                {
                    b.HasOne("IncidenciasAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Ciudadano", b =>
                {
                    b.Navigation("Incidentes");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Incidente", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("IncidenciasAPI.Models.Usuario", b =>
                {
                    b.Navigation("Incidencias");
                });
#pragma warning restore 612, 618
        }
    }
}
